### PR TITLE
Adding possibility to change tag

### PR DESCRIPTION
**Pull request by lucaskatayama**

### CODE REVIEW

**Comment by danawoodman** [comment]
@lucaskatayama thank you for the PR! Noticed that api.md is now gone, can you undo that change? If you fix that, I will merge this!

**Comment by lucaskatayama** [comment]
Done...

**Comment by danawoodman** [comment]
@lucaskatayama quick work! One last request, could you add a small test for the new feature? Thanks!!

**Comment by lucaskatayama** [comment]
Done... 

I was getting a “Cannot render markup in a worker thread” error.
Don't know what is this, so I use this solution 

http://stackoverflow.com/a/26872245/1181036

**Comment by danawoodman** [comment]
Looks like the build is breaking. Perhaps instead of using that import you could wrap the font awesome tag with a `<div>`  instead?

**Comment by lucaskatayama** [comment]
I did it... But I don't understand why it worked ...

**Comment by danawoodman** [comment]
Thanks @lucaskatayama! Merging 🍻

**Comment by danawoodman** [comment]
FYI, I think it needed a parent node since we're running tests in a non-browser environment (eg no `<body>` tag

**Comment by lucaskatayama** [comment]
humm... but why the other test didn't fail?

**Comment by danawoodman** [comment]
Not 100% sure, let me know if you figure it out 😄

**Comment by danawoodman** [comment]
Release in `v1.3.1` on npm!

**Comment by lucaskatayama** [comment]
LOL... XD

**Pull request merged**
