### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by server-monitor**

### CODE REVIEW

**Comment by danawoodman** [comment]
@server-monitor thanks for the fix! 

It's probably not obvious, but this typo can actually be found in here:  https://github.com/danawoodman/react-fontawesome/blob/master/src/index.js#L17

Since the `api.md` is automatically generated, we need to fix it in the JSDocs instead 😄 

If you fix that line and then run `npm run dist` and commit the changes, I'll happily accept this PR!

**Comment by danawoodman** [comment]
Closing until I get a reply from @server-monitor

**Comment by server-monitor** [comment]
Sorry I lost track of this.

**Comment by danawoodman** [comment]
@server-monitor no problem, feel free to update and reopen and I will merge 😄

**Pull request closed without merging**
